const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('maxx', {
  getSnapshot: () => ipcRenderer.invoke('get-snapshot'),
  syncNow: () => ipcRenderer.invoke('sync-now'),
  exportUsage: () => ipcRenderer.invoke('export-usage'),
  refreshProvider: (id) => ipcRenderer.invoke('refresh-provider', id),
  getConfig: () => ipcRenderer.invoke('get-config'),
  getDiagnostics: () => ipcRenderer.invoke('get-diagnostics'),
  setLogLevel: (level) => ipcRenderer.invoke('set-log-level', level),
  copyLogPath: () => ipcRenderer.invoke('copy-log-path'),
  resetSettings: () => ipcRenderer.invoke('reset-settings'),
  getCliStatus: () => ipcRenderer.invoke('get-cli-status'),
  installCli: () => ipcRenderer.invoke('install-cli'),
  uninstallCli: () => ipcRenderer.invoke('uninstall-cli'),
  getPricingFallbackOptions: () => ipcRenderer.invoke('get-pricing-fallback-options'),
  getProxySettings: () => ipcRenderer.invoke('get-proxy-settings'),
  setProxySettings: (payload) => ipcRenderer.invoke('set-proxy-settings', payload),
  getOpenUsagePrefs: () => ipcRenderer.invoke('get-openusage-prefs'),
  setOpenUsagePrefs: (patch) => ipcRenderer.invoke('set-openusage-prefs', patch),
  getSystemPreferences: () => ipcRenderer.invoke('get-system-preferences'),
  onSystemPreferences: (cb) => ipcRenderer.on('system-preferences', (_e, prefs) => cb(prefs)),
  registerGlobalShortcut: (accelerator) => ipcRenderer.invoke('register-global-shortcut', accelerator),
  copyBurnCardPng: (payload) => ipcRenderer.invoke('copy-burn-card-png', payload),
  getSyncStatus: () => ipcRenderer.invoke('get-sync-status'),
  setHistorySync: (value) => ipcRenderer.invoke('set-history-sync', value),
  onHistorySyncStatus: (cb) => ipcRenderer.on('history-sync-status', (_e, status) => cb(status)),
  getCapturePrivacyStatus: () => ipcRenderer.invoke('get-capture-privacy-status'),
  onCapturePrivacyStatus: (cb) => ipcRenderer.on('capture-privacy-status', (_e, status) => cb(status)),
  prepareResetCredit: (payload) => ipcRenderer.invoke('codex:prepare-reset-credit', payload),
  redeemResetCredit: (payload) => ipcRenderer.invoke('codex:redeem-reset-credit', payload),
  detectProviders: () => ipcRenderer.invoke('detect-providers'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  saveBurnPreferences: (preferences) => ipcRenderer.invoke('save-burn-preferences', preferences),
  setMissions: (enabled) => ipcRenderer.invoke('set-missions', enabled),
  onSnapshot: (cb) => ipcRenderer.on('snapshot', (_e, snap) => cb(snap)),
  onPopoverShown: (cb) => ipcRenderer.on('popover-shown', () => cb()),
  close: () => ipcRenderer.send('close-popover'),
  setPopoverMode: (mode) => ipcRenderer.invoke('set-popover-mode', mode),
  setPopoverHeight: (height) => ipcRenderer.invoke('set-popover-height', height),
  openConfigFile: () => ipcRenderer.send('open-config-file'),
  openDebugLog: () => ipcRenderer.send('open-debug-log'),
  openSite: () => ipcRenderer.send('open-site'),
  openProviderLink: (id, kind) => ipcRenderer.invoke('open-provider-link', { id, kind }),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  revealPath: (targetPath) => ipcRenderer.invoke('reveal-path', targetPath),
  forgeIdeas: () => ipcRenderer.invoke('forge-ideas'),
  forgeFeedback: (payload) => ipcRenderer.invoke('forge-feedback', payload),
  forgeStart: (idea) => ipcRenderer.invoke('forge-start', idea),
  forgeCopy: (idea) => ipcRenderer.invoke('forge-copy', idea),
  missionContext: () => ipcRenderer.invoke('mission-context'),
  missionPickFolder: () => ipcRenderer.invoke('mission-pick-folder'),
  missionPreflight: (payload) => ipcRenderer.invoke('mission-preflight', payload),
  modelFitRecommend: (payload) => ipcRenderer.invoke('model-fit-recommend', payload),
  missionCopyGoal: (payload) => ipcRenderer.invoke('mission-copy-goal', payload),
  missionStartProject: (payload) => ipcRenderer.invoke('mission-start-project', payload),
  burnIdeas: () => ipcRenderer.invoke('burn-ideas'),
  burnCopy: (idea) => ipcRenderer.invoke('burn-copy', idea),
  burnStart: (idea) => ipcRenderer.invoke('burn-start', idea),
  backlogMissions: () => ipcRenderer.invoke('backlog-missions'),
  backlogStart: (payload) => ipcRenderer.invoke('backlog-start', payload),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  scanContextBloat: (providerId) => ipcRenderer.invoke('scan-context-bloat', providerId),
  coachVerdicts: () => ipcRenderer.invoke('coach-verdicts'),
  licenseState: () => ipcRenderer.invoke('license-state'),
  licenseActivate: (payload) => ipcRenderer.invoke('license-activate', payload),
  licenseDeactivate: () => ipcRenderer.invoke('license-deactivate'),
  getUpdateStatus: () => ipcRenderer.invoke('get-update-status'),
  getUpdatePreferences: () => ipcRenderer.invoke('get-update-preferences'),
  setUpdatePreferences: (patch) => ipcRenderer.invoke('set-update-preferences', patch),
  checkUpdates: () => ipcRenderer.invoke('check-updates'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_e, s) => cb(s)),
  getApiKeyState: () => ipcRenderer.invoke('get-api-key-state'),
  setApiKey: (id, key) => ipcRenderer.invoke('set-api-key', { id, key }),
  startCopilotLogin: () => ipcRenderer.invoke('start-copilot-login'),
  completeCopilotLogin: (id) => ipcRenderer.invoke('complete-copilot-login', id),
})
