const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('maxx', {
  getSnapshot: () => ipcRenderer.invoke('get-snapshot'),
  syncNow: () => ipcRenderer.invoke('sync-now'),
  exportUsage: () => ipcRenderer.invoke('export-usage'),
  refreshProvider: (id) => ipcRenderer.invoke('refresh-provider', id),
  getConfig: () => ipcRenderer.invoke('get-config'),
  detectProviders: () => ipcRenderer.invoke('detect-providers'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  setMissions: (enabled) => ipcRenderer.invoke('set-missions', enabled),
  onSnapshot: (cb) => ipcRenderer.on('snapshot', (_e, snap) => cb(snap)),
  onPopoverShown: (cb) => ipcRenderer.on('popover-shown', () => cb()),
  close: () => ipcRenderer.send('close-popover'),
  setPopoverMode: (mode) => ipcRenderer.invoke('set-popover-mode', mode),
  setPopoverHeight: (height) => ipcRenderer.invoke('set-popover-height', height),
  openConfigFile: () => ipcRenderer.send('open-config-file'),
  openDebugLog: () => ipcRenderer.send('open-debug-log'),
  openSite: () => ipcRenderer.send('open-site'),
  openProviderLink: (id, kind) => ipcRenderer.invoke('open-provider-link', { id, kind }),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  revealPath: (targetPath) => ipcRenderer.invoke('reveal-path', targetPath),
  forgeIdeas: () => ipcRenderer.invoke('forge-ideas'),
  forgeFeedback: (payload) => ipcRenderer.invoke('forge-feedback', payload),
  forgeStart: (idea) => ipcRenderer.invoke('forge-start', idea),
  forgeCopy: (idea) => ipcRenderer.invoke('forge-copy', idea),
  missionContext: () => ipcRenderer.invoke('mission-context'),
  missionPickFolder: () => ipcRenderer.invoke('mission-pick-folder'),
  missionPreflight: (payload) => ipcRenderer.invoke('mission-preflight', payload),
  modelFitRecommend: (payload) => ipcRenderer.invoke('model-fit-recommend', payload),
  missionCopyGoal: (payload) => ipcRenderer.invoke('mission-copy-goal', payload),
  missionStartProject: (payload) => ipcRenderer.invoke('mission-start-project', payload),
  burnIdeas: () => ipcRenderer.invoke('burn-ideas'),
  burnCopy: (idea) => ipcRenderer.invoke('burn-copy', idea),
  burnStart: (idea) => ipcRenderer.invoke('burn-start', idea),
  backlogMissions: () => ipcRenderer.invoke('backlog-missions'),
  backlogStart: (payload) => ipcRenderer.invoke('backlog-start', payload),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  scanContextBloat: (providerId) => ipcRenderer.invoke('scan-context-bloat', providerId),
  coachVerdicts: () => ipcRenderer.invoke('coach-verdicts'),
  getUpdateStatus: () => ipcRenderer.invoke('get-update-status'),
  checkUpdates: () => ipcRenderer.invoke('check-updates'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_e, s) => cb(s)),
  getApiKeyState: () => ipcRenderer.invoke('get-api-key-state'),
  setApiKey: (id, key) => ipcRenderer.invoke('set-api-key', { id, key }),
  startCopilotLogin: () => ipcRenderer.invoke('start-copilot-login'),
  completeCopilotLogin: (id) => ipcRenderer.invoke('complete-copilot-login', id),
})
